services:
  postgres:
    image: postgres:15
    container_name: catalogo-servicos
    environment:
      POSTGRES_DB: catalogo_servicos
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: